# Урок 3. NumPy и Pandas

Домашнее задание: работа с массивами NumPy, таблицами Pandas и мини-аналитика
по успеваемости группы.

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 20)

## Часть 1. NumPy

In [2]:
scores = np.array([78, 95, 60, 88, 73, 100, 54, 69, 82, 91, 47, 76, 85, 90, 66])
print("Массив оценок:", scores)
print("Количество студентов:", scores.size)

Массив оценок: [ 78  95  60  88  73 100  54  69  82  91  47  76  85  90  66]
Количество студентов: 15

In [3]:
print("Средняя оценка:", round(scores.mean(), 2))
print("Максимальная:", scores.max())
print("Минимальная:", scores.min())

Средняя оценка: 76.93
Максимальная: 100
Минимальная: 47

In [4]:
print("Оценки выше 80:", scores[scores > 80])
print("Оценки ниже 60:", scores[scores < 60])

Оценки выше 80: [ 95  88 100  82  91  85  90]
Оценки ниже 60: [54 47]

In [5]:
raised = scores * 1.1
print("После повышения на 10%:", raised.round(1))

limited = np.clip(raised, 0, 100)
print("С ограничением до 100:", limited.round(1))

После повышения на 10%: [ 85.8 104.5  66.   96.8  80.3 110.   59.4  75.9  90.2 100.1  51.7  83.6
  93.5  99.   72.6]
С ограничением до 100: [ 85.8 100.   66.   96.8  80.3 100.   59.4  75.9  90.2 100.   51.7  83.6
  93.5  99.   72.6]

In [6]:
passing = 70
passed = scores[scores >= passing]
print("Проходной балл:", passing)
print("Сдали:", passed.size, "из", scores.size)
print("Процент сдавших:", round(passed.size / scores.size * 100, 1), "%")

Проходной балл: 70
Сдали: 10 из 15
Процент сдавших: 66.7 %

## Часть 2. Pandas

In [7]:
students = pd.DataFrame({
    "name": ["Ali", "Amina", "Dias", "Dana", "Timur",
             "Aisha", "Nurlan", "Elena", "Serik", "Madina", "Arman", "Zarina"],
    "group": ["RA-521", "RA-521", "RA-521", "RA-522", "RA-522", "RA-522",
              "RA-521", "RA-522", "RA-521", "RA-522", "RA-521", "RA-522"],
    "age": [18, 19, 18, 20, 19, 18, 21, 19, 20, 18, 19, 20],
    "python_score": [78, 95, 60, 88, 73, 100, 54, 69, 82, 91, 47, 76],
    "math_score": [70, 88, 65, 92, 60, 95, 58, 74, 80, 85, 52, 81],
    "attendance": [92, 98, 64, 88, 71, 100, 55, 83, 90, 95, 48, 79],
})
students

      name   group  age  python_score  math_score  attendance
0      Ali  RA-521   18            78          70          92
1    Amina  RA-521   19            95          88          98
2     Dias  RA-521   18            60          65          64
3     Dana  RA-522   20            88          92          88
4    Timur  RA-522   19            73          60          71
5    Aisha  RA-522   18           100          95         100
6   Nurlan  RA-521   21            54          58          55
7    Elena  RA-522   19            69          74          83
8    Serik  RA-521   20            82          80          90
9   Madina  RA-522   18            91          85          95
10   Arman  RA-521   19            47          52          48
11  Zarina  RA-522   20            76          81          79

In [8]:
students.head()

    name   group  age  python_score  math_score  attendance
0    Ali  RA-521   18            78          70          92
1  Amina  RA-521   19            95          88          98
2   Dias  RA-521   18            60          65          64
3   Dana  RA-522   20            88          92          88
4  Timur  RA-522   19            73          60          71

In [9]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          12 non-null     str
 1   group         12 non-null     str
 2   age           12 non-null     int64
 3   python_score  12 non-null     int64
 4   math_score    12 non-null     int64
 5   attendance    12 non-null     int64
dtypes: int64(4), str(2)
memory usage: 708.0 bytes

In [10]:
students.describe()

             age  python_score  math_score  attendance
count  12.000000     12.000000   12.000000    12.00000
mean   19.083333     76.083333   75.000000    80.25000
std     0.996205     16.472889   14.103513    17.19474
min    18.000000     47.000000   52.000000    48.00000
25%    18.000000     66.750000   63.750000    69.25000
50%    19.000000     77.000000   77.000000    85.50000
75%    20.000000     88.750000   85.750000    92.75000
max    21.000000    100.000000   95.000000   100.00000

In [11]:
print("Средний балл по Python:", round(students["python_score"].mean(), 2))
print("Средний балл по математике:", round(students["math_score"].mean(), 2))

Средний балл по Python: 76.08
Средний балл по математике: 75.0

In [12]:
students["average_score"] = ((students["python_score"] + students["math_score"]) / 2).round(2)
students["passed"] = students["average_score"] >= 70
students

      name   group  age  python_score  math_score  attendance  average_score  passed
0      Ali  RA-521   18            78          70          92           74.0    True
1    Amina  RA-521   19            95          88          98           91.5    True
2     Dias  RA-521   18            60          65          64           62.5   False
3     Dana  RA-522   20            88          92          88           90.0    True
4    Timur  RA-522   19            73          60          71           66.5   False
5    Aisha  RA-522   18           100          95         100           97.5    True
6   Nurlan  RA-521   21            54          58          55           56.0   False
7    Elena  RA-522   19            69          74          83           71.5    True
8    Serik  RA-521   20            82          80          90           81.0    True
9   Madina  RA-522   18            91          85          95           88.0    True
10   Arman  RA-521   19            47          52          48           49.5   False
11  Zarina  RA-522   20            76          81          79           78.5    True

In [13]:
print("Сдали:")
print(students[students["passed"]][["name", "group", "average_score"]])

Сдали:
      name   group  average_score
0      Ali  RA-521           74.0
1    Amina  RA-521           91.5
3     Dana  RA-522           90.0
5    Aisha  RA-522           97.5
7    Elena  RA-522           71.5
8    Serik  RA-521           81.0
9   Madina  RA-522           88.0
11  Zarina  RA-522           78.5

In [14]:
print("Не сдали:")
print(students[~students["passed"]][["name", "group", "average_score"]])

Не сдали:
      name   group  average_score
2     Dias  RA-521           62.5
4    Timur  RA-522           66.5
6   Nurlan  RA-521           56.0
10   Arman  RA-521           49.5

In [15]:
print("Посещаемость ниже 70:")
print(students[students["attendance"] < 70][["name", "attendance", "average_score"]])

Посещаемость ниже 70:
      name  attendance  average_score
2     Dias          64           62.5
6   Nurlan          55           56.0
10   Arman          48           49.5

In [16]:
best = students.loc[students["average_score"].idxmax()]
worst_attendance = students.loc[students["attendance"].idxmin()]
print("Лучший студент:", best["name"], "со средним", best["average_score"])
print("Самая низкая посещаемость:", worst_attendance["name"], "-", worst_attendance["attendance"], "%")

Лучший студент: Aisha со средним 97.5
Самая низкая посещаемость: Arman - 48 %

In [17]:
by_group = students.groupby("group")[["python_score", "math_score", "average_score", "attendance"]].mean().round(2)
by_group

        python_score  math_score  average_score  attendance
group
RA-521         69.33       68.83          69.08        74.5
RA-522         82.83       81.17          82.00        86.0

In [18]:
students.sort_values("average_score", ascending=False)[
    ["name", "group", "average_score", "attendance", "passed"]
]

      name   group  average_score  attendance  passed
5    Aisha  RA-522           97.5         100    True
1    Amina  RA-521           91.5          98    True
3     Dana  RA-522           90.0          88    True
9   Madina  RA-522           88.0          95    True
8    Serik  RA-521           81.0          90    True
11  Zarina  RA-522           78.5          79    True
0      Ali  RA-521           74.0          92    True
7    Elena  RA-522           71.5          83    True
4    Timur  RA-522           66.5          71   False
2     Dias  RA-521           62.5          64   False
6   Nurlan  RA-521           56.0          55   False
10   Arman  RA-521           49.5          48   False

## Часть 3. Мини-аналитика

In [19]:
total = len(students)
passed_count = int(students["passed"].sum())
group_best = by_group["average_score"].idxmax()
risk = students[students["attendance"] < 70]["name"].tolist()

print(f"Всего студентов: {total}")
print(f"Средний балл по всей группе: {students['average_score'].mean().round(2)}")
print(f"Сдали: {passed_count} ({round(passed_count / total * 100, 1)}%)")
print(f"Лучший результат: {best['name']} — {best['average_score']}")
print(f"Лучшая группа: {group_best}")
print(f"В зоне риска по посещаемости: {risk}")

Всего студентов: 12
Средний балл по всей группе: 75.54
Сдали: 8 (66.7%)
Лучший результат: Aisha — 97.5
Лучшая группа: RA-522
В зоне риска по посещаемости: ['Dias', 'Nurlan', 'Arman']

### Вывод

Средняя успеваемость группы держится около 75 баллов, то есть чуть выше
проходного порога в 70. Сдали больше половины студентов, но запас небольшой:
несколько человек находятся прямо на границе, и падение на 3–5 баллов переведёт
их в число несдавших.

Лучший результат показал студент с самым высоким средним баллом по двум
предметам, и у него же одна из самых высоких посещаемостей. Это первый признак
связи между присутствием на занятиях и итоговой оценкой.

В зоне риска находятся студенты с посещаемостью ниже 70 процентов — у всех у них
средний балл заметно ниже группового. Группа RA-521 и RA-522 отличаются по
среднему результату, и разрыв объясняется в основном этими отстающими.

Для будущей AI-модели полезными признаками выглядят посещаемость, баллы по
отдельным предметам и возраст. Дополнительно пригодились бы количество сданных
домашних заданий, время, потраченное на практику, и результаты промежуточных
тестов — они позволили бы предсказывать итоговую оценку заранее, а не
констатировать её по факту.